version: "3.9"

services:
  # https://docs.gitlab.com/ee/install/docker.html
  gitlab:
    image: 'gitlab/gitlab-ee:14.4.1-ee.0'
    restart: always
    container_name: gitlab
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 1022
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '1022:22'
      - '80:80'
      - '443:443'
    volumes:
      - '${GITLAB_HOME}/config:/etc/gitlab'
      - '${GITLAB_HOME}/logs:/var/log/gitlab'
      - '${GITLAB_HOME}/data:/var/opt/gitlab'
    networks:
      - appnet

networks:
  appnet:
    name: appnet
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
