FROM php:8.2.1-fpm-bullseye
RUN apt-get update && apt-get install -y \
		libfreetype6-dev \
		libjpeg62-turbo-dev \
		libpng-dev \
		libpq-dev \
		librdkafka-dev \
	&& docker-php-ext-configure gd --with-freetype --with-jpeg \
	&& docker-php-ext-install -j$(nproc) pdo_pgsql pdo_mysql exif gd \
	&& pecl install rdkafka \
	&& docker-php-ext-enable rdkafka
