FROM debian:latest
WORKDIR /var/www
RUN apt-get update \
    && apt-get install -y \
        net-tools \
        iputils-ping \
        # netcat-openbsd \
    && apt-get install -y \
        redis \
        nginx \
        # postgresql \
        # mariadb-server \
    && apt-get install -y \
        php8.2 \
        php8.2-fpm \
        php8.2-mysql \
        php8.2-pgsql \
        php8.2-mongodb \
        php8.2-mbstring \
        php8.2-zip \
        php8.2-xml \
        php8.2-curl \
        php8.2-gd \
        php8.2-bcmath \
        php8.2-gmp \
        php8.2-redis \
        php8.2-intl \
        php8.2-xdebug \
    && echo "alias ll='ls -al'" >> /root/.bashrc
