version: "3.9"

services:

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - ./database:/var/lib/mysql
      #- db-mysql:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER:-dev}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!Secret!}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!Secret!}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
    networks:
      - appnet

networks:
  appnet:
    name: appnet
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16

volumes:
  db-mysql: