version: "3.9"

services:
  nginx:
    container_name: app-nginx
    image: nginx:1.23
    volumes:
      - ./docs/docker/conf.d/app.conf:/etc/nginx/conf.d/app.conf
      - .:/app
    depends_on:
      - "php"
    links:
      - php
    ports:
      - "${APP_PORT:-8000}:8080"
    networks:
      - appnet

  php:
    container_name: app-php
    image: php:8.1.12-fpm-alpine
    volumes:
      - .:/app
    expose:
      - "9000"
    networks:
      - appnet

  composer:
    container_name: app-composer
    image: composer:2.4
    command: composer update
    volumes:
      - $PWD:/app
      - $SSH_AUTH_SOCK:/ssh-auth.sock
    environment:
      SSH_AUTH_SOCK: /ssh-auth.sock

  mysql:
    container_name: app-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      #- ./var/db-mysql:/var/lib/mysql
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-dev}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!Secret!}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!Secret!}
    networks:
      - appnet

networks:
  appnet:
    name: appnet
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
