version: "3.9"

services:

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server
    ports:
      - "${CLICKHOUSE_HTTP_PORT:-18123}:8123"
      - "${CLICKHOUSE_PORT:-19000}:9000"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - ./var/data/:/var/lib/clickhouse/
      - ./var/logs/:/var/log/clickhouse-server/
    environment:
      CLICKHOUSE_INIT_TIMEOUT: 60
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-dev}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-!Secret!}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-app}
    networks:
      - appnet

networks:
  appnet:
    name: appnet
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16

volumes:
  db-clickhouse: