FROM php:8.1.12-fpm-alpine
RUN apk add libpq-dev zlib-dev libpng-dev icu-dev libxml2-dev php81-pecl-rdkafka \
    && docker-php-ext-install -j$(nproc) pdo_pgsql pdo_mysql exif gd intl soap \
    && ln -s /usr/lib/php81/modules/rdkafka.so /usr/local/lib/php/extensions/no-debug-non-zts-20210902/rdkafka.so \
    && docker-php-ext-enable rdkafka
