version: "3.9"

services:
  # https://hub.docker.com/_/postgres
  postgres:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION:-15.1}-alpine
    restart: always
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      #- ./var/db-postgres:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - appnet

networks:
  appnet:
    name: appnet
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
