FROM php:8.2.1-fpm-bullseye
RUN apt-get update && apt-get install -y \
		libzip-dev \
		libfreetype6-dev \
		libjpeg62-turbo-dev \
		libpng-dev \
		libpq-dev \
		librdkafka-dev \
		libicu-dev \
	&& docker-php-ext-configure gd --with-freetype --with-jpeg \
	&& docker-php-ext-install -j$(nproc) pdo_pgsql pdo_mysql mysqli intl exif gd zip \
	&& pecl install rdkafka \
	&& docker-php-ext-enable rdkafka

## SEE:
# pecl install redis
# echo "extension=redis.so" > /usr/local/etc/php/conf.d/docker-php-ext-redis.ini
